# Generated by Django 5.2.7 on 2025-10-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('pages', models.IntegerField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
